export const ALL_CATEGORIES = [
  "Business & Marketing",
  "Entrepreneurship",
  "Startups",
  "Digital Marketing",
  "E-commerce",
  "Social Media Marketing",
  "SEO (Search Engine Optimization)",
  "Branding & Advertising",
  "Freelancing & Remote Work",
  "Productivity & Time Management",
  "Business Trends",
  "Technology & AI",
  "Artificial Intelligence",
  "Machine Learning",
  "Blockchain & Crypto",
  "Cybersecurity",
  "Software Development",
  "Mobile Apps",
  "Gadgets & Reviews",
  "Cloud Computing",
  "Web Development",
  "Tech News & Innovations",
  "News & Current Affairs",
  "World News",
  "Politics",
  "Economy & Finance",
  "Environment",
  "Science & Research",
  "Space & Astronomy",
  "Health Policy & Medical Advances",
  "Health & Lifestyle",
  "Mental Health",
  "Fitness & Exercise",
  "Nutrition & Diet",
  "Wellness & Mindfulness",
  "Sleep & Recovery",
  "Self-improvement",
  "Relationships & Psychology",
  "Fashion & Beauty",
  "Style & Trends",
  "Skincare & Makeup",
  "Men’s Fashion",
  "Sustainable Fashion",
  "Celebrity Styles",
  "Finance & Investment",
  "Personal Finance",
  "Cryptocurrency",
  "Stock Market",
  "Real Estate",
  "Budgeting & Saving",
  "Passive Income",
  "Home & Living",
  "Home Decor",
  "Gardening",
  "Minimalism",
  "DIY Projects",
  "Smart Homes",
  "Travel & Adventure",
  "Destinations",
  "Budget Travel",
  "Travel Tips & Hacks",
  "Luxury Travel",
  "Local Culture",
  "Food & Travel",
  "Food & Cooking",
  "Recipes",
  "Nutrition & Healthy Eating",
  "Street Food",
  "World Cuisine",
  "Kitchen Tips",
  "Entertainment & Gaming",
  "Movies & TV Shows",
  "Music",
  "Gaming",
  "Celebrities & Pop Culture",
  "Anime & Comics",
  "Education & Career",
  "Study Tips",
  "Career Development",
  "Online Learning",
  "Motivation & Mindset",
  "Interview Tips",
  "Skill Development",
  "Sustainability & Environment",
  "Climate Change",
  "Renewable Energy",
  "Eco-friendly Living",
  "Green Technology",
  "Wildlife & Conservation",
  "Motivation & Personal Growth",
  "Success Stories",
  "Life Lessons",
  "Daily Habits",
  "Positive Thinking",
  "Overcoming Challenges",
  "Science & Innovation",
  "Space Exploration",
  "Physics & Chemistry",
  "Biology & Genetics",
  "New Discoveries",
  "Scientific Debates",
  "Relationships & Society",
  "Dating & Love",
  "Family & Parenting",
  "Social Media Culture",
  "Human Behavior",
  "Communication Skills",
  "AI-Generated Creative Content",
  "Poems",
  "Short Stories",
  "Quotes & Affirmations",
  "Scriptwriting",
  "Product Descriptions",
  "YouTube Video Ideas",
];

export const MAIN_CATEGORIES = [
  "Business & Marketing",
  "Technology & AI",
  "News & Current Affairs",
  "Health & Lifestyle",
  "Fashion & Beauty",
  "Finance & Investment",
  "Home & Living",
  "Travel & Adventure",
  "Food & Cooking",
  "Entertainment & Gaming",
  "Education & Career",
  "Sustainability & Environment",
  "Motivation & Personal Growth",
  "Science & Innovation",
  "Relationships & Society",
  "AI-Generated Creative Content",
];
